version="0.3.2"

[scripts]
build-tailwind-dev = [
    "tailwindcss -c ./tailwind.config.js -o ./tailwind.css"
]

tailwind-watch = [
    "tailwindcss -c ./tailwind.config.js -o ./tailwind.css --watch"
]

build-tailwind-prod = [
    "NODE_ENV=production tailwindcss -c ./tailwind.config.js -o ./tailwind.css --minify"
]

## ignoring tailwind.css as tailwind will write to it and will caouse unecessary additional trunk reload
trunk= [
    "trunk serve --open --port=8081 -i ./tailwind.css"
]

## Builds Tailwind CSS for development usage
setup.subcommands.tailwind = "bonnie build-tailwind-dev"
setup.subcommands.prompt-tailwind = "echo \"Have you installed the Tailwind CLI globally with 'npm i -g tailwindcss' or 'yarn global add tailwindcss'?\""
setup.order = """
tailwind {
    Failure => prompt-tailwind
}
"""
